mini_shop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('order/', views.view_order, name='order'),
    path('add/', views.add_to_cart, name='add_to_cart',),
    path('', views.cart, name='cart',),
]

mini_shop/catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        '<int:product_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path('sort/', views.sort, name='sort'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
]

mini_shop/mini_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mini_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_shop/catalog/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Product(models.Model):
    image = models.ImageField(
        upload_to='image/',
        blank=True
    )
    name = models.CharField(max_length=50)
    text = models.TextField()
    price = models.FloatField()
    pub_date = models.DateTimeField()

    def __str__(self):
        return self.text

class Comment(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    rating = models.PositiveSmallIntegerField(
        verbose_name='Рейтинг'
    )

    class Meta:
        ordering = ('-pub_date'),
        verbose_name = 'Комментарий'

    def __str__(self):
        return self.text

mini_shop/catalog/forms.py
from django import forms
from django.forms import RadioSelect

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text', 'rating')
        labels = {
            'text': 'Текст комментария',
        }
        widgets = {
            'rating': RadioSelect(
                choices=[
                    (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')
                ]
            ),
        }
        help_texts = {
            'text': 'Текст комментария',
        }

mini_shop/catalog/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect

from catalog.forms import CommentForm
from catalog.models import Product


def paginator(request, products_list):
    paginator = Paginator(products_list, settings.SLICE)
    page_number = request.GET.get('page', 1)
    products = paginator.get_page(page_number)
    return products

def index(request):
    template = 'catalog/index.html'
    products_list = Product.objects.order_by('price')
    products = paginator(request, products_list)
    context = {
        'products': products,
    }
    return render(request, template, context)


def sort(request):
    template = 'catalog/index.html'
    products_list = Product.objects.order_by('-price')
    products = paginator(request, products_list)
    context = {
        'products': products,
    }
    return render(request, template, context)


def product_detail(request, product_id):
    template = 'catalog/product_detail.html'
    product = get_object_or_404(Product, pk=product_id)
    comments = product.comments.all()

    context = {
        'product': product,
        'form': CommentForm(),
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def add_comment(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.product = product
        comment.save()
    return redirect('catalog:product_detail', product_id=product_id)

mini_shop/templates/catalog/index.html
{% extends 'base.html' %}

{% load thumbnail %}
{% load static %}

{% block content %}

<div class="container">
    <div class="header">
      <h1>Mini shop</h1>
    </div>

<aside>
    <p>Сортировка
    <a href="{% url 'catalog:sort'%}">| по убыванию цены </a>
    <a href="{% url 'catalog:index'%}">| по возрастанию цены</a></p></aside>

    <div class="content">
    {% for product in products %}
        <div class="phone">
        <h4>{{ product.name }}</h4>
        {% thumbnail product.image "250x250" crop="center" upscale=True as im %}
            <img src="{{ im.url }}">
        {% endthumbnail %}
        <p>Цена: {{ product.price }}</p>
            {% include 'cart/add_to_cart.html' %}
            <a href="{% url 'catalog:product_detail' product.pk %}">подробная информация</a>
        </div>
      {% endfor %}
        {% include 'includes/paginator.html' %}
    </div>
  </div>
{% endblock %}

mini_shop/templates/catalog/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}

{% block title %}  {% endblock %}

{% block content %}
<div class="container">
    <div class="row centered mt mb">
        <div class="col-lg-8 col-lg-offset-2">

            <div class="phone">
                <h4>{{ product.name }}</h4>
                {% thumbnail product.image "250x250" crop="center" upscale=True as im %}
                <img src="{{ im.url }}">
                {% endthumbnail %}
                <p>Цена: {{ product.price }}</p>
                <p>Описание: {{ product.text }}</p>
                <p>Дата изготовления: {{ product.pub_date|date:"d E Y" }}</p>
            </div>


            {% for comment in comments %}
            <h4>Отзывы:</h4>
            <div class="media mb-4">
                <div class="media-body">
                    <h5 class="mt-0">
                        {{ comment.author.username }}
                    </h5>
                    <p>
                        Отзыв: {{ comment.text }}
                    </p>
                    <p>
                    <hr>
                    {% for comment in product.comments.get_queryset%}
                    <p>Рейтинг: {{ comment.rating}}</p>
                    {% endfor %}
                    <hr>
                    </p>
                    {{ comment.pub_date|date:"d E Y" }}
                </div>
            </div>
            {% endfor %}

            {% if user.is_authenticated %}
            <div class="card my-4">
                <h5 class="card-header">Оставьте отзыв:</h5>
                <div class="card-body">
                    <form method="post" action="{% url 'catalog:add_comment' product.id %}">
                        {% csrf_token %}
                        <div class="form-group mb-2">
                            {{ form.text }}
                        </div>
                        {% for raiting in form.rating %}
                        {{ raiting }}
                        {% endfor %}
                        <div>
                            <button type="submit" class="btn btn-primary">Отправить</button>
                        </div>
                    </form>
                </div>
            </div>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}