mini_shop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('order/', views.view_order, name='order'),
    path('add/', views.add_to_cart, name='add_to_cart',),
    path('', views.cart, name='cart',),
]

mini_shop/catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        '<int:product_id>/comment/',
        views.add_comment, name='add_comment'
    ),
    path('sort/', views.sort, name='sort'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
]

mini_shop/mini_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mini_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mini_shop/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change_form'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset_form'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

mini_shop/templates/includes/footer.html
<footer>
        <div id="footerwrap">
            <div class="container">
                <div class="row centered">
                    <div class="col-lg-3">
                        <p><b>© Copyright <span style="color:purple">Mini shop</span></b></p>
                    </div>

                </div>

            </div>
        </div>
</footer>
    </div>
</div>

mini_shop/templates/includes/header.html
{% load static %}
<header>
<nav class="navbar navbar-light" style="background-color: lightgrey">
  <a class="navbar-brand" href="{% url 'catalog:index' %}">
  <img src="{% static 'img/logo.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
  <span style="color:purple">Mini shop</span></a>


  {% with request.resolver_match.view_name as view_name %}
  <ul class="nav nav-pills">
    <li class="nav-item">
      <a class="nav-link {% if view_name  == 'cart:view_cart' %}
      active
      {% endif %}"
      href="{% url 'cart:cart' %}">Корзина</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {% if view_name  == 'about:author' %}
      active
      {% endif %}"
      href="{% url 'about:author' %}">О нас</a>
    </li>
    {% if request.user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link link-light
      {% if view_name  == 'users:password_change_form' %}
        active
      {% endif %}"
      href="{% url 'users:password_change_form' %}">Изменить пароль</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
    </li>
    <li>
      Пользователь: {{ user.username }}
    </li>
  {% else %}
    <li class="nav-item ">
      <a class="nav-link link-light
      {% if view_name  == 'users:login' %}
        active
      {% endif %}"
      href="{% url 'users:login' %}">Войти</a>
    </li>
    <li class="nav-item">
      <a class="nav-link link-light
      {% if view_name  == 'users:signup' %}
        active
      {% endif %}"
      href="{% url 'users:signup' %}">Регистрация</a>
    </li>
  {% endif %}
  </ul>
  {% endwith %}
</nav>
</header>

mini_shop/templates/includes/paginator.html
{% if products.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if products.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ products.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in products.paginator.page_range %}
        {% if products.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if products.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ products.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ products.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}